### ISSUE TITLE
register does not work

### ISSUE THREAD

**Issue by husqar** [oyooyo/keyble#1]
[root@hawkstar husqar]# keyble-registeruser --qr_code_data XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX --user_name hsqr 
Press and hold "Unlock" button until the yellow light flashes in order to enter pairing mode
Registering user on Smart Lock with address "00:1a:22:0a:1c:14", card key "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" and serial "NEQ1064762"...

Nothing morge happens on my system...

**Comment by oyooyo** [comment]
Sorry to hear that. What operating system and version of Node.js are you using?

The few people that I know of who've tried this software yet did not report any problems with user registration, so I must admit I currently have no clue what might the problem in your case. :-(

You could try placing `DEBUG=*` ahead of the `keyble-registeruser` command, like `DEBUG=* keyble-registeruser --qr_code_data ...`. The debug output is not very useful yet, but it's the only thing I can currently think of that might help understanding this issue.
Except for some bluetooth MAC addresses, there should be no sensitive information in the actual debug output. So as long as you XXXXXX the QR-Code data and the card key like you already did, it should be okay to post the debug output.

**Comment by husqar** [comment]
I'm using Fedora28, a UD100 Bluetooth Stick and Node.js v8.11.0.

**Comment by husqar** [comment]
I've got this output now:

Registering user on Smart Lock with address "00:1a:22:0a:1c:14", card key "XXXXXXXXXXXXXXXXXXXXXXXXXXXXX" and serial "NEQ1064762"...
  hci setting filter to: 1600000020c10000000000400000 +0ms
  hci set event mask - writing: 01010c08fffffbff07f8bf3d +3ms
  hci set le event mask - writing: 010120081f00000000000000 +0ms
  hci read local version - writing: 01011000 +0ms
  hci write LE host supported - writing: 016d0c020100 +1ms
  hci read LE host supported - writing: 016c0c00 +0ms
  hci read bd addr - writing: 01091000 +0ms
  hci set scan enabled - writing: 010c20020001 +1ms

**Comment by oyooyo** [comment]
I just tried reinstalling keyble and may have run into the very same issue.
After the
`Registering user on Smart Lock with address "00:1a:22:0a:1c:14", card key "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" and serial "NEQ1064762"...`
output, did the program hang, or did it exit?

**Comment by husqar** [comment]
It exits.

**Comment by oyooyo** [comment]
Okay, then I'm indeed running into the same issue.
I believe to have figured out one part of the problem: Passing the QR-code data directly on the command line doesn't seem to work yet. I guess I never tried that way, I always used the
`zbarcam --raw | keyble-registeruser`
version.
But apparantly this is not the only problem, I'm now getting another problem instead. I assume I've messed something up when I published one of the recent versions.

I'll try to resolve this issue at the weekend. Thanks a lot for reporting this bug!

**Comment by husqar** [comment]
ok it works now after I pass the QR Data via pipe but it seem like the UD100 stick does not support LE..

although it should...

I'll try it with a raspberry later..

**Comment by oyooyo** [comment]
In case you were getting some `noble warning: unknown peripheral XXXXXXXXXXX` message, everything is fine - that is the issue I'm currently also running in, and that is definitely a bug in the current code.

**Comment by husqar** [comment]
it works for me now

**Comment by Ircama** [comment]
I have not verified any issue on a *Raspberry Pi Zero W* with Raspbian O.S.

I decoded the QR code through a smartphone with a standard QR scan App.

I tested both the `-n` and the `-q` options of *keyble-registeruser*.

(Notice that the *registeruser* process is currently [very slow](https://github.com/oyooyo/keyble/blob/master/registeruser.coffee#L56).)

**Comment by oyooyo** [comment]
I believe the mentioned issues are all solved in the current version, so I'm closing this issue for now.
