### ISSUE TITLE
Update README with notice to close the smartphone app

### ISSUE THREAD

**Issue by nanosonde** [oyooyo/keyble#12]
Hi!

I am using the lock together with the iOS app.
Now I have tried keyble with the lock.

You should mention in the README that while dealing with keyble, it is better to close the app.
The BLE peripheral that is built into the lock does not seem to handle more than one concurrent BLE connection at a time. 
Trying to keep the app open while using keyble tools seems to lead to strange behaviour where commands time out and registering a user causes problems.

After having made sure that the iOS app is closed, everyhting worked as expected.

From my BLE knowledge and experiences I know that for simple BLE peripherals it is common to only support one concurrent connection only at the same time. Newer BLE peripherals which follow more recent version of the bluetooth spec (>=4.2) MAY support more concurrent connections at the same time.

**Comment by oyooyo** [comment]
Thanks for the good hint. I've updated the README accordingly.

In the past, some people reported issues similar to what you described ("commands time out and registering a user causes problems"), and I could not help them. Now I wonder if maybe their problems had to do with this...
