### ISSUE TITLE
Nodemcu / esp32 compatibility

### ISSUE THREAD

**Issue by Chillerbuy** [oyooyo/keyble#14]
Hi,

due to the low price i think the lock would be optimal in combination with a cheap controller. 
Is there a way to run this on Nodemcu or will there be a future release for that?

**Comment by oyooyo** [comment]
Hi,

Someone else started to port keyble over to the ESP32.
https://github.com/MariusSchiffer/esp32-keyble

It is said to not work reliable yet though, but I did not personally try it out yet.
