### ISSUE TITLE
QR code

### ISSUE THREAD

**Issue by Sigatris** [oyooyo/keyble#19]
Hello.  
I bought a used e-q3 KEY-BLE at the internet auction.  Unfortunately, I do not have a card with a QR code for it.  
I realized that the content of the code is the MAC address, followed by the serial number of the device.  What is the middle string and is it possible to generate a QR sign at all, is the device suitable for rubbish?  
I contacted the manufacturer's website, but he refuses to generate the code. 
 I will be grateful for any help.  
Best regards!

**Comment by oyooyo** [comment]
You're right about the content of the the QR-Code:
The first part is the MAC address, the last part is the serial number.

Now comes the bad news: The middle part is a 128bit AES key that is unique for every device. It is required for registering the users that can use the lock. Without it, you cannot create any user account, and thus will have no control over the lock whatsoever.

I am not aware of anything you could do. Maybe with the right kind of electronical equipment it would be possible to somehow extract the key from the microcontroller, I don't know, but it's probably not even worth the effort.

I'm afraid your device is really pretty much just garbage right now. :-( Have you tried complaining to the seller of the internet auction? Even if he pointed out that he doesn't have the key card anymore, he should have also made clear what the consequences are, namely that the device is completely unusable without it.
