### ISSUE TITLE
[DE] Projekteinbindung in ioBroker

### ISSUE THREAD

**Issue by overfl0w72** [oyooyo/keyble#2]
Hi,
ich schreibe hier mal auf Deutsch.. Ich bin vor zwei Tagen auf dein Projekt aufmerksam geworden und da ich im Besitz des besagten Türschlosses bin und mein Zuhause "Smart" ist, dank der Software ioBroker hier ganz Stumpf die Frage: Würdest Du der Community helfen deinen Code in einen Adapter zu packen für ioBroker?

Der Adapter ist bereits requested, aber Du bist scheinbar schon tief in der Materie :)

https://github.com/ioBroker/AdapterRequests/issues/114

Danke dir im Voraus

**Comment by oyooyo** [comment]
Hi & Danke für den Hinweis auf den ioBroker-Adapter-Request!
Dort habe ich eben schon geschrieben, dass ich grundsätzlich da gerne helfe - da ioBroker ja offenbar ebenfalls in Node.js geschrieben ist, scheint es mir im ersten Moment kein allzu grosser Aufwand zu sein, die Chancen stehen also gut.

Da ich (so wie ich [das](https://github.com/ioBroker/ioBroker.template#requirements) verstehe) für einen ioBroker-Adapter allerdings eh ein neues Repository anlegen muss, und der Adapter nicht Teil des "keyble"-Repositories sein kann, schliesse ich diesen Issue hier aber erst einmal.
